### ISSUE TITLE
Kodi icon always resets

### ISSUE THREAD

**Issue by timbooo** [Jocala/adbFire#7]
Since a few days the Kodi icon is always resets back to the ikono TV icon after changing it via Llama options in adbFire. Is it just me or did Amazon change something and the current method no longer works?

**Comment by Jocala** [comment]
New version 1.16 has a fix that may work for this. However, it's possible that Amazon/Ikono is proactively working to stop the icon replacement from working. Time will tell.

**Comment by timbooo** [comment]
Been running the new version for a few days, the new fix seems to work.
